### ISSUE TITLE
Ubuntu 12.04 Running Chromium

### ISSUE THREAD

**Issue by DiagonalArg** [UNINETT/Foodle#47]
I can see the link when I produce a new foodle, but I can't cut it (to then later paste it).  Neither Control-A nor the mouse work to select, Control-C doesn't work to copy.

**Comment by peter-** [comment]
1. Works for me, tested with an old Chromium 37 on 12.04 TLS.
2. Trivial workaround: Just click the "Continue to Foodle" button on that screen, which will redirect the browser to the URL of the newly created Foodle. Then copy the URL from the browser's location bar.

**Comment by DiagonalArg** [comment]
K.  Thanks.
