### ISSUE TITLE
Domain foodl.org lost, drop related links in the interest of user safety?

### ISSUE THREAD

**Issue by hartwork** [Uninett/Foodle#68]
Hi!

I just learned that domain https://foodl.org/ now serves weird casino gaming content but it is still linked here prominently. Please replace or drop the links so that people do not run the risk of getting malware or something. Thank you!

Best, Sebastian

**Comment by sokai** [comment]
This IMHO is urgent! **push**

**Comment by hartwork** [comment]
@lunkwill42 can you help out or get us in touch with someone?

Given the easy to overlook but clear warning "We do not re[comm]end to install and use this software" in the readme, maybe the repository would also be best marked as archived?

**Comment by sokai** [comment]
@andreassolberg, @jaimeperez, @ttsirkia, @stweil : Because for me it's *something important* (to make the Internet secure in places where it is possible for us) I ping you, the devs, with this comment directly *#forgivemeplz*

BR!

**Comment by stweil** [comment]
I'm afraid that @andreassolberg is the only maintainer who can remove the links to the old domain and archive this repository.

**Comment by hartwork** [comment]
@andreassolberg any news?

**Comment by stweil** [comment]
Andreas last activity on GitHub was in January 2024 in another repository. I now try to contact him there. If this also does not work, asking the GitHub support would be the next step.

**Comment by stweil** [comment]
@jaimeperez, do you have maintainer rights to fix this issue?

**Comment by andreassolberg** [comment]
Links should be gone now. Thanks.

**Comment by hartwork** [comment]
Thank you!
